[package]
name = "arma3_wiki_fetch"
version = "0.1.0"
authors = ["Brett Mayson"]
edition = "2021"

[lints]
workspace = true

[dependencies]
arma3_wiki = { path = "../clients/rust" }
arma3_wiki_lib = { path = "../lib" }

httpdate = { version = "1.0.3" }
octocrab = { version = "0.32.0" }
regex = { version = "1.10.2" }
reqwest = { version = "0.11.22" }
serde_yaml = { workspace = true }
tokio = { version = "1.34.0", features = ["full"] }
urlencoding = { version = "2.1.3" }
