[package]
name = "arma3-wiki-fetch"
version = "0.1.0"
authors = ["Brett Mayson"]
edition = "2021"

[lints]
workspace = true

[dependencies]
arma3-wiki = { path = "../clients/rust" }
arma3-wiki-lib = { path = "../lib" }

httpdate = { version = "1.0.3" }
octocrab = { version = "0.36.0" }
regex = { version = "1.10.4" }
reqwest = { version = "0.12.2" }
serde_yaml = { workspace = true }
tokio = { version = "1.36.0", features = ["full"] }
urlencoding = { version = "2.1.3" }
