[package]
name = "a3_wiki_fetch"
version = "0.1.0"
authors = ["Brett Mayson"]
edition = "2021"

[dependencies]
a3_wiki_lib ={ path = "../lib" }

httpdate = { version = "1.0.3" }
octocrab = { version = "0.32.0" }
regex = { version = "1.10.2" }
reqwest = { version = "0.11.22" }
serde_yaml = { version = "0.9.27" }
tempdir = { version = "0.3.7" }
tokio = { version = "1.34.0", features = ["full"] }
urlencoding = { version = "2.1.3" }
