id: Local
description: ''
params:
- name: group
  type: Group
argument_loc: Unspecified
effect_loc: Unspecified
examples:
- "_group addEventHandler [\"Local\", {\n\tparams [\"_group\", \"_isLocal\"];\n}];"
