name: local
desc: |-
  Check if given unit is local on the computer in multiplayer games - see {{Link|Multiplayer Scripting#Locality}}.<br>
  This can be used to determine on which computer some code must be run. In single player all objects are local.
multiplayer_note: |-
  A few things to note [[Multiplayer Scripting#General information about locality|amongst others]]:
  * A game logic / module is always local to the server
  * Terrain objects are local to every machine
groups:
- Multiplayer
syntax:
- call: !Unary object
  ret:
    type: Boolean
  params:
  - name: object
    type: !OneOf
    - - Object
      - null
    - - Group
      - null
argument_loc: Global
effect_loc: Unspecified
since:
  flashpoint: '1.0'
  flashpoint_elite: '1.0'
  arma1: '1.0'
  arma2: '1.0'
  arma2oa: '1.50'
  tkoh: '1.0'
  arma3: '0.50'
examples:
- "<sqf>\nif (not local _unit) then\n{\n\thint format [\"%1 is remote\", name _unit];\n};\n</sqf>"
- <sqf>_isLocalGroup = local group _unit;</sqf>
- |-
  Sets variable's [[Variables#Scopes|scope]]:
  <sqf>
  // from Arma 2 v1.00 until Arma 3v1.54
  local _myVariable = 42;

  // since {{arma3}} v1.54
  private _myVariable = 42;
  </sqf>
see_also:
- Arma
- '3:'
- Event
- Handlers#Local|"Local"
- Event
- Handler
- owner
- setOwner
