name: productVersion
desc: |-
  Returns the product's friendly name, identifier, version and build number.
  {{Feature|arma3|The command has been upgraded to also returns branch identifier, whether or not the game was launched using mods, the platform and the architecture.}}
groups:
- System
syntax:
- call: Nular
  ret:
    type: Unknown
  params: []
argument_loc: Unspecified
effect_loc: Unspecified
since:
  arma2oa: '1.62'
  tkoh: '1.0'
  arma3: '0.50'
examples:
- <sqf>hint str productVersion; // would return ["Arma 2 OA", "arma2oa", 162, 95208] on Arma 2 OA 1.62.95208</sqf>
- <sqf>hint str productVersion; // ["Arma 3", "Arma3", 137, 128764, "Development", false, "Windows"]</sqf>
- '<sqf>format ["%1.%2", (productVersion select 2) * 0.01 toFixed 2, productVersion select 3]; // returns version e.g.: "2.00.146773"</sqf>'
- <sqf>productVersion params ["_name", "_nameShort", "_version", "_buildNumber", "_buildType", "_isModded", "_platform", "_architecture", "_steamBranchName"];</sqf>
see_also:
- supportInfo
- requiredVersion
