name: productVersion
description: |-
  Returns the product's friendly name, identifier, version and build number.
  {{Feature|arma3|The command has been upgraded to also returns branch identifier, whether or not the game was launched using mods, the platform and the architecture.}}
groups:
- System
syntax:
- call: Nular
  ret:
  - Unknown
  - null
  params: []
argument_loc: Unspecified
effect_loc: Unspecified
since:
  arma_2_arrowhead:
    major: 1
    minor: 62
  take_on_helicopters:
    major: 1
    minor: 0
  arma_3:
    major: 0
    minor: 50
examples:
- hint str productVersion; // would return ["Arma 2 OA", "arma2oa", 162, 95208] on Arma 2 OA 1.62.95208
- hint str productVersion; // ["Arma 3", "Arma3", 137, 128764, "Development", false, "Windows"]
- ' format ["%1.%2", (productVersion select 2) * 0.01 toFixed 2, productVersion select 3]; // returns version e.g.: "2.00.146773"'
