name: productVersion
description: |-
  Returns the product's friendly name, identifier, version and build number.
  {{Feature|arma3|The command has been upgraded to also returns branch identifier, whether or not the game was launched using mods, the platform and the architecture.}}
groups:
- System
syntax:
- call: Nular
  ret:
  - Unknown
  - |-
    product name
    * nameShort: [[String]] - product short name
    * version: [[Number]] - product version number
    * buildNumber: [[Number]] - product build number
    * {{GVI|arma3|1.00|size= 0.75}} buildType: [[String]] - build type, can be {{hl|"Stable"}}, {{hl|"Development"}}, {{hl|"Diag"}} or {{hl|"Profile"}}
    * {{GVI|arma3|1.00|size= 0.75}} isModded: [[Boolean]] - is the product running with mods ([[true]]) or vanilla ([[false]])
    * {{GVI|arma3|1.00|size= 0.75}} platform: [[String]] - can be {{hl|"Windows"}}, {{hl|"Linux"}} or {{hl|"OSX"}}
    * {{GVI|arma3|1.68|size= 0.75}} architecture: [[String]] - {{hl|"x64"}} for 64bit or {{hl|"x86"}} for 32bit
    * {{GVI|arma3|2.20|size= 0.75}} steamBranchName: [[String]] - {{hl|""}} (for default/public branch), {{hl|"profiling"}} or {{hl|"development"}}
  params: []
argument_loc: Unspecified
effect_loc: Unspecified
since:
  arma_2_arrowhead:
    major: 1
    minor: 62
  take_on_helicopters:
    major: 1
    minor: 0
  arma_3:
    major: 0
    minor: 50
examples:
- <sqf>hint str productVersion; // would return ["Arma 2 OA", "arma2oa", 162, 95208] on Arma 2 OA 1.62.95208</sqf>
- <sqf>hint str productVersion; // ["Arma 3", "Arma3", 137, 128764, "Development", false, "Windows"]</sqf>
- '<sqf>format ["%1.%2", (productVersion select 2) * 0.01 toFixed 2, productVersion select 3]; // returns version e.g.: "2.00.146773"</sqf>'
- <sqf>productVersion params ["_name", "_nameShort", "_version", "_buildNumber", "_buildType", "_isModded", "_platform", "_architecture", "_steamBranchName"];</sqf>
